# -*- coding: utf-8 -*-
import serial
# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

import calibration_wmd3


alert_map = {0: ["Ошибка", "Длина значений в полях осей не должна превышать 4!"],
             1: ["Внимание", "Калибровка завершена"],
             2: ["Внимание", "Калибровка началась. Ввод будет временно отключен!"],
             3: ["Ошибка", "Нельзя отправлять команды во время работы калибровки!"]}

is_start_calibration = False


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 300))
        MainWindow.setMaximumSize(QtCore.QSize(800, 300))
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(1000, 300))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 741, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setEnabled(True)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.xText = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.xText.setMaximumSize(QtCore.QSize(16777215, 30))
        self.xText.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.xText.setObjectName("xText")
        self.horizontalLayout_6.addWidget(self.xText)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.yText = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.yText.setMaximumSize(QtCore.QSize(16777215, 30))
        self.yText.setObjectName("yText")
        self.horizontalLayout_5.addWidget(self.yText)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.zText = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.zText.setMaximumSize(QtCore.QSize(16777215, 30))
        self.zText.setObjectName("zText")
        self.horizontalLayout_3.addWidget(self.zText)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.home0Btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.home0Btn.setObjectName("home0Btn")
        self.home0Btn.clicked.connect(lambda: self.home_event())
        self.horizontalLayout_4.addWidget(self.home0Btn)
        self.calibBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.calibBtn.setObjectName("calibBtn")
        self.calibBtn.clicked.connect(lambda: self.calibration_event())
        self.horizontalLayout_4.addWidget(self.calibBtn)
        self.startBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.startBtn.setObjectName("startBtn")
        self.startBtn.clicked.connect(lambda: self.start_event())
        self.horizontalLayout_4.addWidget(self.startBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calibration GUI"))
        self.label.setText(_translate("MainWindow", "X:"))
        self.label_2.setText(_translate("MainWindow", "Y:"))
        self.label_3.setText(_translate("MainWindow", "Z:"))
        self.home0Btn.setText(_translate("MainWindow", "Исходное положение"))
        self.calibBtn.setText(_translate("MainWindow", "Калибровка"))
        self.startBtn.setText(_translate("MainWindow", "Запуск"))


    def start_event(self):
        if not is_start_calibration:
            ser = serial.Serial('COM11', 9600, timeout=5)
            if len(self.xText.toPlainText()) > 4 or len(self.yText.toPlainText()) > 4 or len(self.zText.toPlainText()) > 4:
                show_alert_dialog(0)
            else:
                message = f"0deg{self.xText.toPlainText().zfill(5)}.000-{self.yText.toPlainText().zfill(5)}.000-{self.zText.toPlainText().zfill(5)}.000-00000.000-040.0\n"
                ser.write(message.encode())
            ser.close()
        else:
            show_alert_dialog(3)


    def home_event(self):
        if not is_start_calibration:
            ser = serial.Serial('COM11', 9600, timeout=5)
            message = "home0\n"
            ser.write(message.encode())
            ser.close()
        else:
            show_alert_dialog(3)

    def calibration_event(self):
        global is_start_calibration
        show_alert_dialog(2)
        is_start_calibration = True
        calibration_wmd3.start_calibration()


def show_alert_dialog(alert_id):
    msg = QMessageBox()
    msg.setIcon(QMessageBox.Critical)
    msg.setText(alert_map[alert_id][0])
    msg.setInformativeText(alert_map[alert_id][1])
    msg.setWindowTitle(alert_map[alert_id][0])
    msg.exec_()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
